@file:Suppress("MagicNumber")

package com.example.designsystem.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5D6310)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFAFFAF)
val onPrimaryContainerLight = Color(0xFF545904)
val secondaryLight = Color(0xFF5E613D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8EABC)
val onSecondaryContainerLight = Color(0xFF4A4D2A)
val tertiaryLight = Color(0xFF576333)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF3FFCA)
val onTertiaryContainerLight = Color(0xFF4E5A2A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCF9EE)
val onBackgroundLight = Color(0xFF1C1C15)
val surfaceLight = Color(0xFFFCF9EE)
val onSurfaceLight = Color(0xFF1C1C15)
val surfaceVariantLight = Color(0xFFE5E3D0)
val onSurfaceVariantLight = Color(0xFF474839)
val outlineLight = Color(0xFF787868)
val outlineVariantLight = Color(0xFFC8C7B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31312A)
val inverseOnSurfaceLight = Color(0xFFF4F1E6)
val inversePrimaryLight = Color(0xFFC6CD70)
val surfaceDimLight = Color(0xFFDDDACF)
val surfaceBrightLight = Color(0xFFFCF9EE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F4E9)
val surfaceContainerLight = Color(0xFFF1EEE3)
val surfaceContainerHighLight = Color(0xFFEBE8DD)
val surfaceContainerHighestLight = Color(0xFFE5E3D8)

val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF2F3300)
val primaryContainerDark = Color(0xFFD4DB7C)
val onPrimaryContainerDark = Color(0xFF3E4300)
val secondaryDark = Color(0xFFC8CA9D)
val onSecondaryDark = Color(0xFF303213)
val secondaryContainerDark = Color(0xFF3F4120)
val onSecondaryContainerDark = Color(0xFFD5D7AA)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF2A3408)
val tertiaryContainerDark = Color(0xFFCCDB9F)
val onTertiaryContainerDark = Color(0xFF384417)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF14140E)
val onBackgroundDark = Color(0xFFE5E3D8)
val surfaceDark = Color(0xFF14140E)
val onSurfaceDark = Color(0xFFE5E3D8)
val surfaceVariantDark = Color(0xFF474839)
val onSurfaceVariantDark = Color(0xFFC8C7B4)
val outlineDark = Color(0xFF929280)
val outlineVariantDark = Color(0xFF474839)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E3D8)
val inverseOnSurfaceDark = Color(0xFF31312A)
val inversePrimaryDark = Color(0xFF5D6310)
val surfaceDimDark = Color(0xFF14140E)
val surfaceBrightDark = Color(0xFF3A3A32)
val surfaceContainerLowestDark = Color(0xFF0E0F09)
val surfaceContainerLowDark = Color(0xFF1C1C15)
val surfaceContainerDark = Color(0xFF202019)
val surfaceContainerHighDark = Color(0xFF2A2A23)
val surfaceContainerHighestDark = Color(0xFF35352E)
