name: CI

on:
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # 推奨されるディストリビューション

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Setup API Key 
        run: echo "WEB_CLIENT_ID=${{ secrets.WEB_CLIENT_ID }}" >> $GITHUB_ENV

      - name: Create dummy local.properties
        run: echo "" > local.properties

      - name: Run detekt
        run: ./gradlew detekt

